SET IDENTITY_INSERT [dbo].[Laptops] ON
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (1, N'Inspiron-15', N'Inspiron 15 Non-Touch $299.99', N'$279.99 with Dell Preferred Account and $20 instant off. Discount applied during checkout.* DVD/CD drive not included.', 4, 320, 15, N'Intel® Celeron® Processor (Dual Core)', N'Windows 8.1', CAST(299.99 AS Decimal(18, 2)), N'Inspiron-15.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (2, N'Inspiron-15', N'Inspiron 15 Non-Touch $429.99', N'Get all the performance you need with the 3rd Gen Intel® Core™ i3 processor. Also enjoy burning files, installing software and watching your favorites films with a built-in optical drive included.??', 4, 500, 15, N'4th Generation Intel® Core™ i3 Processor', N'Windows 7 Home Premium', CAST(429.99 AS Decimal(18, 2)), N'Inspiron-15.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (3, N'Inspiron-15', N'Inspiron 15 Touch $499.99', N'Touch Screen: Immerse yourself in the Windows 8 experience with this touch screen laptop.', 4, 500, 15, N'4th Generation Intel® Core™ i3 Processor', N'Windows 8.1', CAST(499.99 AS Decimal(18, 2)), N'Inspiron-15.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (4, N'Inspiron-17', N'Inspiron 17 Non-Touch $449.99', N'Good desktop replacement with a 10-key number pad and plenty of processing power to complete your daily tasks.', 4, 500, 17, N'Intel® Pentium® Processor (Dual Core)', N'Windows 8.1', CAST(449.99 AS Decimal(18, 2)), N'Inspiron-17.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (5, N'Inspiron-17', N'Inspiron 17 Non-Touch $529.99', N'Enjoy the stylish design, just over 1" thin, without compromising power. Perfect for watching movies with a spacious 17.3" HD display 4th gen Intel® Core™ i3 processor and Windows 8.', 4, 500, 17, N'4th Generation Intel® Core™ i3 Processor', N'Windows 8.1', CAST(529.99 AS Decimal(18, 2)), N'Inspiron-17.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (6, N'Inspiron-17', N'Inspiron 17 Non-Touch $599.99', N'Includes an upgraded 4th Gen Intel® Core™ i5 processor, Windows 8 and more memory for faster computing and multitasking ablity.', 6, 750, 17, N'4th Generation Intel® Core™ i5 Processor', N'Windows 8.1', CAST(599.99 AS Decimal(18, 2)), N'Inspiron-17.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (7, N'Inspiron-14R', N'Inspiron 14R Touch $749.99', N'Touch Screen: Includes a faster processor, more memory and a larger hard drive for the ultimate computing experience.', 8, 1000, 14, N'4th Generation Intel® Core™ i5 Processor', N'Windows 8.1', CAST(749.99 AS Decimal(18, 2)), N'Inspiron-14R.png')
INSERT INTO [dbo].[Laptops] ([ID], [Name], [Description], [Summary], [Memory], [HardDisk], [ScreenSize], [Processor], [OperatingSystem], [Price], [ImageUrl]) VALUES (8, N'Inspiron-14R', N'Inspiron 14R Touch  $799.99', N'Experience high-performance portability with the Inspiron 14R. It’s thin, light, and built to travel with hours of battery life.', 8, 1000, 14, N'4th Generation Intel® Core™ i5 Processor', N'Windows 8.1', CAST(799.99 AS Decimal(18, 2)), N'Inspiron-14R.png')
SET IDENTITY_INSERT [dbo].[Laptops] OFF
